### ISSUE TITLE
HelloGitHub Badge

### ISSUE THREAD

**Issue by 521xueweihan** [uiwjs/react-login-page#14]
🎉 Congratulations! Your [project](https://hellogithub.com/repository/49e71ff761fc4749bb0bbe87592c458a) has been featured and recommended by the HelloGitHub community. We invite you to join the HelloGitHub Badge Program. Joining will grant you the following privileges:

- **Community Recognition**: The badge indicates that your project has successfully passed the HelloGitHub community's stringent selection and recommendation process.
- **Increased Exposure**: Displaying the badge will draw more traffic to your project, attracting additional users and contributors.
- **Enhanced Interaction**: Users can quickly understand your project through the badge and engage with it (like, comment, bookmark).
- **Feedback Collection**: Gather genuine feedback from a broad user base, aiding in the continuous improvement of your project.
- **Special Identification**: Once verified, your comments will feature a distinctive mark and be prioritized for pinning.

📌 [Click here](https://hellogithub.com/repository/49e71ff761fc4749bb0bbe87592c458a/embed) to wear the badge and join the HelloGitHub Badge Program, allowing your open-source project to shine even brighter.

---

**HelloGitHub** is a community focused on discovering, sharing, and promoting open-source projects. Since its inception in 2016, it has grown from a monthly newsletter into a dynamic community with over **10,000** users. Our footprint extends across multiple content platforms, earning the trust and support of **500,000** fans worldwide.

<img width="1245" alt="截屏2024-06-12 09 29 42" src="https://github.com/No-Chicken/OV-Watch/assets/8255800/7ac6b71e-f052-4f44-88b1-5c772e917348">

**Comment by jaywcjlove** [comment]
@521xueweihan 感谢推荐

**Comment by jaywcjlove** [comment]
<img width="684" alt="image" src="https://github.com/uiwjs/react-login-page/assets/1680273/43cfb2a3-831f-42a2-83e6-50f01c314e34">


如果提供这样小的徽章，我愿意放到项目介绍中 @521xueweihan

**Comment by 521xueweihan** [comment]
@jaywcjlove 嗯嗯，这个我得开发一下，等我开发完再来一战！

**Comment by 521xueweihan** [comment]
@jaywcjlove 极简的小徽章已上线，欢迎认领：

<img width="693" alt="image" src="https://github.com/uiwjs/react-login-page/assets/8255800/4c66b785-829d-444b-b782-27f2c6ac5e1f">

**Comment by jaywcjlove** [comment]
@521xueweihan 已经添加

<img width="677" alt="image" src="https://github.com/uiwjs/react-login-page/assets/1680273/8bd91bc2-13fc-473b-93dd-a89d284ab3e4">

**Comment by 521xueweihan** [comment]
@jaywcjlove 感谢认领，已通过。

<img width="765" alt="image" src="https://github.com/uiwjs/react-login-page/assets/8255800/63cda762-3784-4160-93fc-04dd7116e68f">
